### ISSUE TITLE
player.on("ready")

### ISSUE THREAD

**Issue by brunosiqueira** [FunctionallyLiterate/angular-jwplayer#12]
I'm getting this error every now and then:

```
TypeError: player.on is not a function
    at JWPlayer._renderJWPlayerElement (http://localhost:3001/bower_components/ng-jwplayer/jwplayer.js:77:20)
    at JWPlayer.link (http://localhost:3001/bower_components/ng-jwplayer/jwplayer.js:112:21)
    at http://localhost:3001/bower_components/angular/angular.js:9033:44
    at invokeLinkFn (http://localhost:3001/bower_components/angular/angular.js:9039:9)
    at nodeLinkFn (http://localhost:3001/bower_components/angular/angular.js:8533:11)
    at compositeLinkFn (http://localhost:3001/bower_components/angular/angular.js:7929:13)
    at compositeLinkFn (http://localhost:3001/bower_components/angular/angular.js:7932:13)
    at compositeLinkFn (http://localhost:3001/bower_components/angular/angular.js:7932:13)
    at publicLinkFn (http://localhost:3001/bower_components/angular/angular.js:7809:30)
    at boundTranscludeFn (http://localhost:3001/bower_components/angular/angular.js:7947:16) <jwplayer ng-src="{{ streamPath }}" player-options="options" player-id="myplayer{{user.id}}" class="ng-isolate-scope">
```

**Comment by GuillaumeCisco** [comment]
Where did you find the code ng-jwplayer?
Are you sure it is the right repository and not https://github.com/ampervue/ngJWPlayer instead?
By the way, you should try this code containing updates : https://github.com/GuillaumeCisco/angular-jwplayer

**Comment by brunosiqueira** [comment]
You are right, @GuillaumeCisco . I am sorry for the confusion
